spring:
  application:
    name: CatalogueManagement

  datasource:
    url: jdbc:postgresql://localhost:5433/cataloguemanagement
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
otel:
 
  exporter:
    otlp:
      endpoint: http://localhost:4317
      protocol: grpc

  
  logs:
    exporter: none

  resource:
    attributes:
      service.name: CatalogueManagement

  traces:
    sampler: always_on

